# SPDX-FileCopyrightText: 2015 ownCloud, Inc.
# SPDX-License-Identifier: AGPL-3.0-or-later
filter:
    excluded_paths:
        - 'js/3rdparty*'

imports:
    - javascript
    - php

tools:
    external_code_coverage: true

