<?php return array(
    'root' => array(
        'name' => '__root__',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => 'cfd48c8ab8986bf0b444fede00b5c3f70c0f703a',
        'type' => 'library',
        'install_path' => __DIR__ . '/../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => 'cfd48c8ab8986bf0b444fede00b5c3f70c0f703a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mikehaertl/php-pdftk' => array(
            'pretty_version' => '0.13.1',
            'version' => '0.13.1.0',
            'reference' => '3851b08c1027489e48387d7c14c27bc295d98239',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mikehaertl/php-pdftk',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mikehaertl/php-shellcommand' => array(
            'pretty_version' => '1.7.0',
            'version' => '1.7.0.0',
            'reference' => 'e79ea528be155ffdec6f3bf1a4a46307bb49e545',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mikehaertl/php-shellcommand',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mikehaertl/php-tmpfile' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => '70a5b70b17bc0d9666388e6a551ecc93d0b40a10',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mikehaertl/php-tmpfile',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
